"""
Django settings for smartpxe project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# 修改路径为拆分后的路径。
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)o)a!k!m^)n)i$cue98udsr5^(64gd+^i0g52-s_krbf4q5dp9'

# SECURITY WARNING: don't run with debug turned on in production!
# 由下面进行进行统一环境管理
# DEBUG = True
#
# ALLOWED_HOSTS = ['*',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'install',
    'temp',
    'django_filters',
    'dashboard',
    'task',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smartpxe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smartpxe.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans' # 'en-us'

TIME_ZONE = 'Asia/Shanghai' # 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 控制当前settings配置状态
# 0 => 开发环境, 1 => 生产环境
CONF_STATUS = 1

if CONF_STATUS:
    print('当前环境为： 生产环境', "+++++++++++++++++++++++++++++++++=")
    DEBUG = False
    ALLOWED_HOSTS = ['*',]
    # 生产环境数据库
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'smartpxe',
            'USER': 'root',
            'PASSWORD': '123456',
            'HOST': '127.0.0.1',
            'PORT': '3306',
        }
    }
    # drf配置
    REST_FRAMEWORK = {
        # 'EXCEPTION_HANDLER': 'utils.exceptions.exception_handler',  # 全局拦截器
        'DEFAULT_AUTHENTICATION_CLASSES': ( # JWT token认证
            'rest_framework_simplejwt.authentication.JWTAuthentication',
        ),
        # 'DEFAULT_PERMISSION_CLASSES': [  # 设置权限策略，
        #     'rest_framework.permissions.IsAuthenticated',  # 设置所有连接都要经过认证
        #     'utils.permissions.CrudModelPermission'
        # ],
        'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
        'DEFAULT_PAGINATION_CLASS': 'utils.paginations.PageNumberPagination',
        'PAGE_SIZE': 5,
    }

    # jwt 认证配置
    from datetime import timedelta
    SIMPLE_JWT = {
        'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),  # jwt授权的token时效
    }

    # 程序基础路径配置
    # 程序基础路径配置
    IMAGES_UPLOADS_DIR = "/tmp"
    SERVER_URL = "http://server_addr" # server.smartpxe.com
    SERVER_API = "http://server_api" # www.smartpxe.com/api/v1
    HTTP_DIR = "/var/www/html/"
    KS_DIR = HTTP_DIR + "ks/"
    PUBLIC_KEY = "public_key"

else:
    print('当前环境为： 开发环境', "+++++++++++++++++++++++++++++++++=")
    DEBUG = True
    ALLOWED_HOSTS = ['*',]
    # 数据库配置
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'smartpxe',
            'USER': 'root',
            'PASSWORD': '123456',
            'HOST': '127.0.0.1',
            'PORT': '3306',
        }
    }
    # 在Django的控制台中打印sql执行语句
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'loggers': {
            'django.db.backends': {
                'handlers': ['console'],
                'level': 'DEBUG',
            },
        },
    }
    # drf配置
    REST_FRAMEWORK = {
        # 'EXCEPTION_HANDLER': 'utils.exceptions.exception_handler',  # 全局拦截器
        # 'DEFAULT_AUTHENTICATION_CLASSES': ( # JWT token认证
        #     'rest_framework_simplejwt.authentication.JWTAuthentication',
        # ),
        # 'DEFAULT_PERMISSION_CLASSES': [  # 设置权限策略，
        #     'rest_framework.permissions.IsAuthenticated',  # 设置所有连接都要经过认证
        #     'utils.permissions.CrudModelPermission'
        # ],
        'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
        'DEFAULT_PAGINATION_CLASS': 'utils.paginations.PageNumberPagination',
        'PAGE_SIZE': 5,
    }

    # jwt认证配置
    # from datetime import timedelta
    # SIMPLE_JWT = {
    #     'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),  # jwt授权的token时效
    # }

    # 程序基础路径配置
    IMAGES_UPLOADS_DIR = "/tmp"
    SERVER_URL = "http://10.10.100.2"
    SERVER_API = "http://10.10.100.2:8000"
    HTTP_DIR = "/var/www/html/"
    KS_DIR = HTTP_DIR + "ks/"
    PUBLIC_KEY = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC3PxjQfN5/1WcEmkoTBnpKTsyJAZQd1lSYoEvtKv87V5prTWEOAhzxZ0P6X8T/xpQXk4o+F0FnsQIm2V5J32vzlsKCd5cEpf+laihBkkPyIpT8whvHC4uy2MCxM9PxT71Thde2o3fk2tIETX2lEcCF1jMMXg58Mv22YMB9kaw1AEXt2aPAnZv5GUwu4Rzk+0DC174vgXr6P7C79/dFPCwpqRSjREEvDusQSOEfE0zxlOS5SxBaRxiB93WWi9UUgQtBKoxhiaSaeJcBBW3EgkIexKCC7Zvnv2+T70/Kcs7EefrsWFKEmLEv/x5VjVCA5n1h4OSXjchw9tTBlYqbCSb082IndNdukbKheJax5fMku608CHl8DOLoZcVyzCFaxNtczpp7Xg/8ji5o29LllV0xqRYOkXZQrp8aG4mk0IfzIZsPfEmTFdDmfR+edLiyG6hK3GESatmYMEWanIAYdalr+HgJqlw9bVcoN97nh+v1J7nxaL4z3s3a2t5W/Cyk3C8= root@pxeserver"
